# Redis deployment with persistence
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ignitabull-redis
  namespace: ignitabull
  labels:
    app: ignitabull-redis
    component: cache
spec:
  replicas: 1
  strategy:
    type: Recreate  # Use Recreate to avoid conflicts with persistent volume
  selector:
    matchLabels:
      app: ignitabull-redis
  template:
    metadata:
      labels:
        app: ignitabull-redis
        component: cache
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
          name: redis
        command:
        - redis-server
        - --appendonly
        - "yes"
        - --appendfsync
        - "everysec"
        - --save
        - "900"
        - "1"
        - --save
        - "300"
        - "10"
        - --save
        - "60"
        - "10000"
        - --maxmemory
        - "256mb"
        - --maxmemory-policy
        - "allkeys-lru"
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ignitabull-secrets
              key: REDIS_PASSWORD
              optional: true
        volumeMounts:
        - name: redis-data
          mountPath: /data
        - name: redis-config
          mountPath: /usr/local/etc/redis/redis.conf
          subPath: redis.conf
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsUser: 999
          runAsGroup: 999
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-pvc
      - name: redis-config
        configMap:
          name: redis-config

---
apiVersion: v1
kind: Service
metadata:
  name: ignitabull-redis-service
  namespace: ignitabull
  labels:
    app: ignitabull-redis
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    app: ignitabull-redis

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: ignitabull
  labels:
    app: ignitabull-redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: ignitabull
  labels:
    app: ignitabull-redis
data:
  redis.conf: |
    # Redis configuration for production
    # Network and security
    bind 0.0.0.0
    protected-mode yes
    port 6379
    timeout 0
    keepalive 300
    
    # Memory management
    maxmemory 256mb
    maxmemory-policy allkeys-lru
    maxmemory-samples 5
    
    # Persistence settings
    save 900 1
    save 300 10
    save 60 10000
    stop-writes-on-bgsave-error yes
    rdbcompression yes
    rdbchecksum yes
    dbfilename dump.rdb
    dir /data
    
    # AOF (Append Only File) settings
    appendonly yes
    appendfilename "appendonly.aof"
    appendfsync everysec
    no-appendfsync-on-rewrite no
    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 64mb
    aof-load-truncated yes
    aof-use-rdb-preamble yes
    
    # Logging
    loglevel notice
    logfile ""
    syslog-enabled no
    
    # Client settings
    tcp-backlog 511
    tcp-keepalive 300
    
    # Memory optimization
    hash-max-ziplist-entries 512
    hash-max-ziplist-value 64
    list-max-ziplist-size -2
    list-compress-depth 0
    set-max-intset-entries 512
    zset-max-ziplist-entries 128
    zset-max-ziplist-value 64
    
    # Performance tuning
    hz 10
    dynamic-hz yes
    
    # Security (uncomment if using AUTH)
    # requirepass your-redis-password
    
    # Disable dangerous commands in production
    rename-command FLUSHDB ""
    rename-command FLUSHALL ""
    rename-command KEYS ""
    rename-command DEBUG ""
    rename-command CONFIG "CONFIG_b835f8f2a5c7"