# Secrets template (actual values should be managed externally)
apiVersion: v1
kind: Secret
metadata:
  name: ignitabull-secrets
  namespace: ignitabull
type: Opaque
stringData:
  # Database credentials
  DATABASE_URL: "postgresql://username:password@postgres:5432/ignitabull"
  
  # External service credentials
  SUPABASE_URL: "https://your-project.supabase.co"
  SUPABASE_ANON_KEY: "your-anon-key"
  SUPABASE_SERVICE_ROLE_KEY: "your-service-role-key"
  
  # Neo4j credentials
  NEO4J_URI: "bolt://neo4j:7687"
  NEO4J_USERNAME: "neo4j"
  NEO4J_PASSWORD: "password"
  
  # Redis URL
  REDIS_URL: "redis://redis:6379"
  
  # JWT secret
  JWT_SECRET: "your-super-secret-jwt-key"
  
  # Email service
  RESEND_API_KEY: "your-resend-api-key"
  
  # Amazon API credentials
  AMAZON_SP_CLIENT_ID: "your-amazon-client-id"
  AMAZON_SP_CLIENT_SECRET: "your-amazon-client-secret"
  
  # AI service credentials
  OPENAI_API_KEY: "your-openai-api-key"
  ANTHROPIC_API_KEY: "your-anthropic-api-key"